var products1 = [
  { 
  название: "tovar 1", 
  описание: "Описание 1", 
  цена: 10, 
  data: new Date("2023-07-01") 
},
  { 
  название: "Товар 2", 
  описание: "Описание 2", 
  цена: 20, 
  data: new Date("2023-07-02") 
},
  { 
  название: "Товар 3", 
  описание: "Описание 3", 
  цена: 30, 
  data: new Date("2023-07-03") 
}
];

var products2 = [
  { 
  catlogo: "url('https://administrati0n.github.io/data-one/xcodel.png')", 
  add1: "url('https://administrati0n.github.io/data-one/firebbasel.png')", 
  add2: "url('https://administrati0n.github.io/data-one/xcodepack.png')", 
  accentcolor: "rgba(33, 172, 222, 1.0)", 
  accentcolor1: "rgb(5, 28, 34)", 
  accentcolor2: "rgb(12, 72, 94)", 
  catlogo1: "url('https://administrati0n.github.io/data-one/appstorel.png')", 
  logoproj: "url('https://administrati0n.github.io/data-one/Starter Pack.png')", 
  название: "Starter Pack", 
  описание: "Описание 6", 
  leftT: "Xcode", 
  rightT: "Pack", 
  cost: 60,
  data: new Date("2023-07-05"),
  data0: "2023-07-05"
},
  { 
  catlogo: "url('https://administrati0n.github.io/data-one/xcodel.png')", 
  add1: "url('https://administrati0n.github.io/data-one/firebbasel.png')", 
  add2: "url('https://administrati0n.github.io/data-one/xcodepack.png')", 
  accentcolor: "rgba(33, 172, 222, 1.0)", 
  accentcolor1: "rgb(5, 28, 34)", 
  accentcolor2: "rgb(12, 72, 94)", 
  catlogo1: "url('https://administrati0n.github.io/data-one/appstorel.png')", 
  logoproj: "url('https://administrati0n.github.io/data-one/Starter Pack.png')", 
  название: "Starter Pack", 
  описание: "Описание 6", 
  leftT: "Xcode", 
  rightT: "Pack", 
  cost: 60,
  data: new Date("2023-07-05"),
  data0: "2023-07-02"
},
  { 
  catlogo: "url('https://administrati0n.github.io/data-one/xcodel.png')", 
  add1: "url('https://administrati0n.github.io/data-one/firebbasel.png')", 
  add2: "url('https://administrati0n.github.io/data-one/xcodepack.png')", 
  accentcolor: "rgba(33, 172, 222, 1.0)", 
  accentcolor1: "rgb(5, 28, 34)", 
  accentcolor2: "rgb(12, 72, 94)", 
  catlogo1: "url('https://administrati0n.github.io/data-one/appstorel.png')", 
  logoproj: "url('https://administrati0n.github.io/data-one/Starter Pack.png')", 
  название: "Starter Pack", 
  описание: "Описание 6", 
  leftT: "Xcode", 
  rightT: "Pack", 
  cost: 60,
  data: new Date("2023-07-05"),
  data0: "2023-07-02"
},
  { 
  catlogo: "url('https://administrati0n.github.io/data-one/xcodel.png')", 
  add1: "url('https://administrati0n.github.io/data-one/firebbasel.png')", 
  add2: "url('https://administrati0n.github.io/data-one/xcodepack.png')", 
  accentcolor: "rgba(33, 172, 222, 1.0)", 
  accentcolor1: "rgb(5, 28, 34)", 
  accentcolor2: "rgb(12, 72, 94)", 
  catlogo1: "url('https://administrati0n.github.io/data-one/appstorel.png')", 
  logoproj: "url('https://administrati0n.github.io/data-one/Starter Pack.png')", 
  название: "Starter Pack", 
  описание: "Описание 6", 
  leftT: "Xcode", 
  rightT: "Pack", 
  cost: 60,
  data: new Date("2023-07-05"),
  data0: "2023-07-02"
},
  { 
  catlogo: "url('https://administrati0n.github.io/data-one/xcodel.png')", 
  add1: "url('https://administrati0n.github.io/data-one/firebbasel.png')", 
  add2: "url('https://administrati0n.github.io/data-one/xcodepack.png')", 
  accentcolor: "rgba(33, 172, 222, 1.0)", 
  accentcolor1: "rgb(5, 28, 34)", 
  accentcolor2: "rgb(12, 72, 94)", 
  catlogo1: "url('https://administrati0n.github.io/data-one/appstorel.png')", 
  logoproj: "url('https://administrati0n.github.io/data-one/Starter Pack.png')", 
  название: "Starter Pack", 
  описание: "Описание 6", 
  leftT: "Xcode", 
  rightT: "Pack", 
  cost: 60,
  data: new Date("2023-07-05"),
  data0: "2023-07-02"
},
  { 
  catlogo: "url('https://administrati0n.github.io/data-one/xcodel.png')", 
  add1: "url('https://administrati0n.github.io/data-one/firebbasel.png')", 
  add2: "url('https://administrati0n.github.io/data-one/xcodepack.png')", 
  accentcolor: "rgba(33, 172, 222, 1.0)", 
  accentcolor1: "rgb(5, 28, 34)", 
  accentcolor2: "rgb(12, 72, 94)", 
  catlogo1: "url('https://administrati0n.github.io/data-one/appstorel.png')", 
  logoproj: "url('https://administrati0n.github.io/data-one/Starter Pack.png')", 
  название: "Starter Pack", 
  описание: "Описание 6", 
  leftT: "Xcode", 
  rightT: "Pack", 
  cost: 60,
  data: new Date("2023-07-05"),
  data0: "2023-07-02"
},
  { 
  catlogo: "url('https://administrati0n.github.io/data-one/xcodel.png')", 
  add1: "url('https://administrati0n.github.io/data-one/firebbasel.png')", 
  add2: "url('https://administrati0n.github.io/data-one/xcodepack.png')", 
  accentcolor: "rgba(33, 172, 222, 1.0)", 
  accentcolor1: "rgb(5, 28, 34)", 
  accentcolor2: "rgb(12, 72, 94)", 
  catlogo1: "url('https://administrati0n.github.io/data-one/appstorel.png')", 
  logoproj: "url('https://administrati0n.github.io/data-one/Starter Pack.png')", 
  название: "Starter Pack", 
  описание: "Описание 6", 
  leftT: "Xcode", 
  rightT: "Pack", 
  cost: 60,
  data: new Date("2023-07-05"),
  data0: "2023-07-02"
},
  { 
  catlogo: "url('https://administrati0n.github.io/data-one/xcodel.png')", 
  add1: "url('https://administrati0n.github.io/data-one/firebbasel.png')", 
  add2: "url('https://administrati0n.github.io/data-one/xcodepack.png')", 
  accentcolor: "rgba(33, 172, 222, 1.0)", 
  accentcolor1: "rgb(5, 28, 34)", 
  accentcolor2: "rgb(12, 72, 94)", 
  catlogo1: "url('https://administrati0n.github.io/data-one/appstorel.png')", 
  logoproj: "url('https://administrati0n.github.io/data-one/Starter Pack.png')", 
  название: "Starter Pack", 
  описание: "Описание 6", 
  leftT: "Xcode", 
  rightT: "Pack", 
  cost: 60,
  data: new Date("2023-07-05"),
  data0: "2023-07-02"
},
  { 
  catlogo: "url('https://administrati0n.github.io/data-one/xcodel.png')", 
  add1: "url('https://administrati0n.github.io/data-one/firebbasel.png')", 
  add2: "url('https://administrati0n.github.io/data-one/xcodepack.png')", 
  accentcolor: "rgba(33, 172, 222, 1.0)", 
  accentcolor1: "rgb(5, 28, 34)", 
  accentcolor2: "rgb(12, 72, 94)", 
  catlogo1: "url('https://administrati0n.github.io/data-one/appstorel.png')", 
  logoproj: "url('https://administrati0n.github.io/data-one/Starter Pack.png')", 
  название: "Starter Pack", 
  описание: "Описание 6", 
  leftT: "Xcode", 
  rightT: "Pack", 
  cost: 60,
  data: new Date("2023-07-05"),
  data0: "2023-07-02"
},
  { 
  catlogo: "url('https://administrati0n.github.io/data-one/xcodel.png')", 
  add1: "url('https://administrati0n.github.io/data-one/firebbasel.png')", 
  add2: "url('https://administrati0n.github.io/data-one/xcodepack.png')", 
  accentcolor: "rgba(33, 172, 222, 1.0)", 
  accentcolor1: "rgb(5, 28, 34)", 
  accentcolor2: "rgb(12, 72, 94)", 
  catlogo1: "url('https://administrati0n.github.io/data-one/appstorel.png')", 
  logoproj: "url('https://administrati0n.github.io/data-one/Starter Pack.png')", 
  название: "Starter Pack", 
  описание: "Описание 6", 
  leftT: "Xcode", 
  rightT: "Pack", 
  cost: 60,
  data: new Date("2023-07-05"),
  data0: "2023-07-02"
},
  { 
  catlogo: "url('https://administrati0n.github.io/data-one/xcodel.png')", 
  add1: "url('https://administrati0n.github.io/data-one/firebbasel.png')", 
  add2: "url('https://administrati0n.github.io/data-one/xcodepack.png')", 
  accentcolor: "rgba(33, 172, 222, 1.0)", 
  accentcolor1: "rgb(5, 28, 34)", 
  accentcolor2: "rgb(12, 72, 94)", 
  catlogo1: "url('https://administrati0n.github.io/data-one/appstorel.png')", 
  logoproj: "url('https://administrati0n.github.io/data-one/Starter Pack.png')", 
  название: "Starter Pack", 
  описание: "Описание 6", 
  leftT: "Xcode", 
  rightT: "Pack", 
  cost: 60,
  data: new Date("2023-07-05"),
  data0: "2023-07-02"
},
  { 
  catlogo: "url('https://administrati0n.github.io/data-one/xcodel.png')", 
  add1: "url('https://administrati0n.github.io/data-one/firebbasel.png')", 
  add2: "url('https://administrati0n.github.io/data-one/xcodepack.png')", 
  accentcolor: "rgba(33, 172, 222, 1.0)", 
  accentcolor1: "rgb(5, 28, 34)", 
  accentcolor2: "rgb(12, 72, 94)", 
  catlogo1: "url('https://administrati0n.github.io/data-one/appstorel.png')", 
  logoproj: "url('https://administrati0n.github.io/data-one/Starter Pack.png')", 
  название: "Starter Pack", 
  описание: "Описание 6", 
  leftT: "Xcode", 
  rightT: "Pack", 
  cost: 60,
  data: new Date("2023-07-05"),
  data0: "2023-07-02"
},
  { 
  catlogo: "url('https://administrati0n.github.io/data-one/xcodel.png')", 
  add1: "url('https://administrati0n.github.io/data-one/firebbasel.png')", 
  add2: "url('https://administrati0n.github.io/data-one/xcodepack.png')", 
  accentcolor: "rgba(33, 172, 222, 1.0)", 
  accentcolor1: "rgb(5, 28, 34)", 
  accentcolor2: "rgb(12, 72, 94)", 
  catlogo1: "url('https://administrati0n.github.io/data-one/appstorel.png')", 
  logoproj: "url('https://administrati0n.github.io/data-one/Starter Pack.png')", 
  название: "Starter Pack", 
  описание: "Описание 6", 
  leftT: "Xcode", 
  rightT: "Pack", 
  cost: 60,
  data: new Date("2023-07-05"),
  data0: "2023-07-06"
}
];

